{
 "title": "mario",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PingURL",
    "query": "SHOW TAG VALUES FROM \"ping\" WITH KEY = \"url\""
   }
  ]
 },
 "panels": [
  {
   "title": "ELB Clasic Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HostCount / BackendConnectionErrors - mpzda i ovo rastavit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HealthyHostCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "BackendConnectionErrors",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "SpilloverCount / SurgeQueueLength - naravit varijable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "SpilloverCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "SurgeQueueLength",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "HTTPCode - rastavit i napravit varijable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Backend_5XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Backend_4XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Backend_3XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Backend_2XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_4XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_5XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "RequestCount / Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RequestCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "Latency",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "NLB Network Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_Client_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_ELB_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_Target_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "ConsumedLCUs / ProcessedBytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Net /Active Flow Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveFlowCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewFlowCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Healthy / Unhealthy Hosts Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*", "TargetGroup": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*", "TargetGroup": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$PingURL Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "PingURL",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "percent_packet_loss" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 3600" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "208.67.222.222" }
       ]
      }
     ]
    },
    {
     "title": "Ping Average Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "url" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
       ]
      }
     ]
    },
    {
     "title": "Packet Loss Percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "url" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "query": "SELECT max(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" = '208.67.222.222' AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "percent_packet_loss" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
       ]
      }
     ]
    },
    {
     "title": "$PingURL Ping",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
     "repeat": "PingURL",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ELB Application Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthy Hosts ($loadbalancername) ????",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "LoadBalancerName": "*" },
       "metricName": "HealthyHostCount",
       "namespace": "AWS/ELB",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Unhealthy Hosts ($targetgroup)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "LoadBalancerName": "*" },
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/ELB",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Auth - treba uredit sa varijablom",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthError",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthFailure",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthRefreshTokenSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthUserClaimsSizeExceeded",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthLatency",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "TLSNegotiationErrorCount - treba uredit sa varijablom",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ClientTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes -treba uredit sa varijablom",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLBCapacityUnits",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "ConnectionCount - ovo treba uredit sa varijablom",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RejectedConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetConnectionErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "RequestCount / TargetResponseTime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RequestCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetResponseTime",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "HTTPCode_Target 5xx",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "HTTPCode_Target 4xx",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "HTTPCode_Target 3xx",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 5xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 4xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 3xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "CloudFront",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / TotalErrorRate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "Requests",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TotalErrorRate",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "4xxErrorRate / 5xxErrorRate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "4xxErrorRate",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Average" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "5xxErrorRate",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "BytesDownloaded / BytesUploaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "BytesDownloaded",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DistributionId": "*", "Region": "Global" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "BytesUploaded",
       "namespace": "AWS/CloudFront",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Billing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated charges",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "Total",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Average" ]
      },
      {
       "alias": "{{ServiceName}}",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD", "ServiceName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Estimated daily charges",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 6 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "Total estimated daily charge",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD" },
       "expression": "IF(m2>0, m2)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "id": "m3",
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "period": "86400",
       "region": "us-east-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Estimated charges by Service",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "{{ServiceName}}",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD", "ServiceName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "period": "1d",
       "region": "us-east-1",
       "statistics": [ "Maximum" ]
      }
     ]
    }
   ]
  }
 ]
}